#ifndef __PakPanel__
#define __PakPanel__

/**
@file
Subclass of BasePAKPanel, which is generated by some idiot.
*/

#include "HLMWADFrames.h"

//// end generated include

#include "TexturePack.h"
#include "HexView.h"

/** Implementing BaseTexturePackPanel */
class PAKPanel : public BasePAKPanel
{

protected:
	void OnPAKListBoxSelected(wxCommandEvent& event);

public:
	/** Constructor */
	PAKPanel(wxWindow* parent, bool isChild = false);
	//// end generated class members

	void LoadPAK(wxInputStream& iStr, wxInt64 size);

private:
	wxVector<wxCharBuffer> files;
	HexView* m_hexView;
	int pakSize = 0;
	bool isPak(wxInputStream &in);

	bool isChild;

};

#endif // __PAKPanel__
